### ISSUE TITLE
Lite version of Event display?

### ISSUE THREAD

**Issue by 153957** [HiSPARC/jsparc#40]
The event display uses about 40% CPU on my MBA. Some computers might not be as 'powerful'. We could make a 'lite' version (optional url argument (hash/query) or switch on the page) of the event display that is less demanding by removing the transitions (simply show the discs for a short time).

**Comment by davidfokkema** [comment]
Certainly something to look into. While my MBP is five years old, amazingly my classroom computer is much slower.

**Comment by 153957** [comment]
7 years later this is no longer much of an issue I think.
