### ISSUE TITLE
Markers misaligned in Firefox/Safari

### ISSUE THREAD

**Issue by 153957** [HiSPARC/jsparc#42]
The event and coincidence markers are not in the correct location in (recent version of) Firefox.
It works fine in Safari..

Im not certain if this is a Firefox bug or something in jSparc.

Works fine in Safari/Chrome/IE

@davidfokkema

**Comment by davidfokkema** [comment]
It works fine in Chrome, too. But that rendering engine is mostly the same as Safari's. I wonder about IE.

**Comment by tomkooij** [comment]
It does not run at all in IE 11.0.22 (just a blank screen)

The debugger complains about Math.log10() not supported. It is indeed not supported: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10

**Comment by 153957** [comment]
Indeed, Chrome works, I have now installed its latest version on station 507.
However, Firefox _used_ to work fine too..

`Math.log()` is supported, as is `Math.LN10`.
So for IE compatibility we should probably just use `Math.log(val) / Math.LN10`
(from: http://stackoverflow.com/a/3019290/1033535)

**Comment by davidfokkema** [comment]
You got to be kidding me! Why is it not yet supported? Oh, well...

**Comment by 153957** [comment]
@tomkooij Can you try it again with IE?

**Comment by tomkooij** [comment]
@153957 Still a blank screen... Nothing suspious in console. Just nothing.

**Comment by 153957** [comment]
MIME types have been fixed on pique. So that should no longer be an issue.

**Comment by 153957** [comment]
The same misalignment also occurs in the built-in browser for the Android Facebook app (Reported by Gerard Osinga).
Perhaps is also uses the Gecko engine?

**Comment by tomkooij** [comment]
It looks like Facebook uses the built-in android webview app/class. Which is some version of WebKit depending on Android version (it is not updated with Chrome/AOSP browser). From Android 5.0 webview version is independent of OS and *can* be updated.

Read: It can be any version of WebKit!

**Comment by 153957** [comment]
I do not know which version Gerard was running.

**Comment by 153957** [comment]
I also see this issue in the latest Safari (11.0.1), and in the latest Firefox (v57).
It still works fine (correctly aligned) in Chrome (62).

**Comment by 153957** [comment]
Fixed in 3ce1e2bd405dd7b8258301531b04938bef367777
