### ISSUE TITLE
Traces do not show on the analysis page

### ISSUE THREAD

**Issue by 153957** [HiSPARC/jsparc#52]
I tried retrieving an example. I did get a coincidence, but the traces were empty:

page:
http://data.hisparc.nl/media/jsparc/jsparc.html

coincidence data:
http://data.hisparc.nl/jsparc/get_coincidence/?session_title=example&session_pin=1337&student_name=test

**Comment by 153957** [comment]
not a jsparc issue but publicdb issue.

**Comment by kaspervd** [comment]
Thanks, Niek will be very happy with this!
